version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=students
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql